import React, { Fragment } from "react";
import Footer from "./footer";
import Head from "next/head";
import SideBar from "./sidebar";
import { Container, HStack, VStack, Box, Flex } from "@chakra-ui/react";
import PageHeading from "./Header/Tabs";
import NavBar from "./Header/NavBar";
import Tabs from "./Header/Tabs";

export default function Layout({
  children,
  pageHeading,
  pageTabs,
  navHeading,
}) {
  return (
    <Fragment>
      <Head>
        <title>Steaman HR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Box w="15vw" h="100vh" bg="teal.100" p={10}>
          <SideBar />
        </Box>

        <Box p={10} w="80vw">
          <NavBar heading={navHeading} />
          <Tabs tablist={pageTabs} />
          <Container h="100vh" maxW="1200px" over>
            {children}
          </Container>

          <Footer />
        </Box>
      </Flex>
    </Fragment>
  );
}
