import React, { Fragment } from "react";
import Head from "next/head";
import SideBar from "./sidebar";
import { Container, HStack, VStack, Box, Flex } from "@chakra-ui/react";
import PageHeading from "./Header/Tabs";
import NavBar from "./Header/NavBar";
import Tabs from "./Header/Tabs";

export default function Layout({
  children,
  pageHeading,
  pageTabs,
  navHeading,
}) {
  return (
    <Fragment>
      <Head>
        <title>Steaman HR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Human resource,HR, Steaman, " />
        <link rel="icon" href="/logo.png" type="image/png" />
      </Head>
      <Flex>
        <Box w="15vw" minH="100vh" bg="#0b665c" p={10}>
          <SideBar />
        </Box>

        <Box p={10} w="80vw">
          <NavBar heading={navHeading} />
          <Tabs tablist={pageTabs} />
          <Container maxW="1200px" minH="100vh">
            {children}
          </Container>
        </Box>
      </Flex>
    </Fragment>
  );
}
